### PR TITLE
Implement a function to iterate over all pending timeouts

### PR DESCRIPTION
**Pull request by nmathewson**
Libevent needed this, and I expect that others will too.

### CODE REVIEW

**Comment by daurnimator** [comment]
Why does libevent even need to know about all the timeouts? Usually you only give it the next expiring one.

**Comment by nmathewson** [comment]
Libevent has a set of functions that need to iterate over all pending events.

**Comment by wahern** [comment]
I've reimplemented the iterator without the need for callbacks. The code is in a new branch, https://github.com/wahern/timeout/tree/timeout_foreach. If it works for you I can merge it.

timeouts_next returns the next timeout, preserving iteration state in the struct timeouts_cursor object. The macro TIMEOUTS_FOREACH can be used similar to TAILQ_FOREACH:

```
TIMEOUTS_FOREACH(to, timeouts, TIMEOUTS_PENDING) {
  ...
}
```

The original branch spoke of both pending and expired timeouts in the declaration comment, but only walked the pending timeouts on the wheel. In the new branch the cursor object has a flags field which is used to select the pending and expired queues

**Comment by nmathewson** [comment]
That branch looks good to me.

**Pull request merged**
